name: Android CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Setup JDK
        uses: actions/setup-java@v4.7.1
        with: 
          java-version: 17
          distribution: 'temurin'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      
        
      - name: Build Project
        run: ./gradlew build
        
      - name: Upload APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          
